---
name: RHNC
version: 0.01
author:
  - 'Jérôme Fenal <jfenal@redhat.com>'
abstract: An OO Red Hat Network Satellite Client.
license: perl
resources:
  license: ~
build_requires:
  Frontier::Client: 0
  Params::Validate: 0
  Test::More: 0
provides:
  RHNC:
    file: lib/RHNC.pm
    version: 0.01
  RHNC::ActivationKey:
    file: lib/RHNC/ActivationKey.pm
    version: 0.01
  RHNC::Channel:
    file: lib/RHNC/Channel.pm
    version: 0.01
  RHNC::Kickstart:
    file: lib/RHNC/Kickstart.pm
    version: 0.01
  RHNC::Org:
    file: lib/RHNC/Org.pm
    version: 0.01
  RHNC::Package:
    file: lib/RHNC/Package.pm
    version: 0.01
  RHNC::Session:
    file: lib/RHNC/Session.pm
    version: 0.01
  RHNC::System:
    file: lib/RHNC/System.pm
    version: 0.01
  RHNC::SystemGroup:
    file: lib/RHNC/SystemGroup.pm
    version: 0.01
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
