---
name: RHNC
version: 0.01
author:
  - 'Jérôme Fenal <jfenal@redhat.com>'
abstract: An OO Red Hat Network Satellite Client.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  Config::IniFiles: 0
  Frontier::Client: 0
  Getopt::Long: 2.37
  IO::Socket::SSL: 0
  Params::Validate: 0
recommends:
  Devel::Cover: 0
  Perl::Critic: 0
  Perl::Tidy: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Script::Run: 0
configure_requires:
  Module::Build: 0.35
provides:
  RHNC:
    file: lib/RHNC.pm
    version: 0.01
  RHNC::ActivationKey:
    file: lib/RHNC/ActivationKey.pm
    version: 0.01
  RHNC::Channel:
    file: lib/RHNC/Channel.pm
    version: 0.01
  RHNC::ConfigChannel:
    file: lib/RHNC/ConfigChannel.pm
    version: 0.01
  RHNC::Errata:
    file: lib/RHNC/Errata.pm
    version: 0.01
  RHNC::Kickstart:
    file: lib/RHNC/Kickstart.pm
    version: 0.01
  RHNC::KickstartTree:
    file: lib/RHNC/KickstartTree.pm
    version: 0.01
  RHNC::Org:
    file: lib/RHNC/Org.pm
    version: 0.01
  RHNC::Package:
    file: lib/RHNC/Package.pm
    version: 0.01
  RHNC::Schedule:
    file: lib/RHNC/Schedule.pm
    version: 0.01
  RHNC::Session:
    file: lib/RHNC/Session.pm
    version: 0.01
  RHNC::System:
    file: lib/RHNC/System.pm
    version: 0.01
  RHNC::System::CustomInfo:
    file: lib/RHNC/System/CustomInfo.pm
    version: 0.01
  RHNC::SystemGroup:
    file: lib/RHNC/SystemGroup.pm
    version: 0.01
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
