RHNC::SystemGroup->as_string
RHNC::System->as_string
RHNC::Kickstart->as_string
RHNC::Kickstart->render

For each object, add a copy_to($rhnc) to copy the object to _another_
Satellite or organisation within the same Satellite.

rhnc-org:
- list_users

rhnc-ak :
- add channels to subscribe
- add packages.arch to package list
- toggle univ_default ?
- change entitlements

rhnc-sg
- add systems from file
- rm systems from file
+ implement rm_systems : done

rhnc-channel
- implement add packages
- add packages from file
- implement rm_packages
- rm packages from file

rhnc-pkg
- search package based on name only (partial/complete)
- search package based on name + version (partial/complete)
- search package based on name + version + release (partial/complete)

rhnc-user :
- create rhnc-user
- modify (setDetails)
- add_user
- del_user
- list_user
- disable_user
- enable_user
- add/remove default_system_group
- add/remove assigned_system_group
- add/remove role


=head1 Quick TODO list.

 Tests :
 - include possibility to test without a Satellite or Spacewalk server

 API :
 - complete API coverage.

 Scripts :
 - complete scripts coverage to allow usage of API from shell.


=head1 Developement Ideas

 With this package, we want to achieve :
 - a command line interface to RHN Satellite
 - automation for export/import task
 
 For systems, we need to :
 - get a list from Satellite, possibly using groups
 - display the list (choose columns ?)
 - FIXME : dumpxml a system to allow for re-registration of the same
   system with same uuid on anonther satellite ?
 - define (and not register, foolproof if uuid not already there)
 
 For system groups, we need to 
 - list
 - define
 - assign systems to a group
 - dumpxml (definition, except membership)
 - loadxml
 
 For activations keys:
 - list
 - display
 - dumpxml (1 or selection)
 - define from dumpxml
 - Prerequisites :
   - Channels & sub-channels (verify at import ??)
   - package list (not to verify, too huge, could be done)
   - Configuration channels (rhncfg-manager)
   - system groups
 
 For kickstarts
 - Kickstart profiles
 - Kickstart snippets (could be done from outside satellite, by
   dumping files into Cobbler directories?)

 For kickstart snippets
 - list
 - dumpxml (one, many)
 - loadxml
 
 Keys : GPG & SSL keys
 Namespace : kickstart.keys
     * listAllKeys
     * create
     * delete
     * getDetails

 System Profiles :
 - list
 - dumpxml
 - loadxml

 Conservation lists:
 - list
 - dumpxml
 - loadxml
 
 Custom System information
 - list all keys (and dump the list)
 - recreate one or all keys from XML
 
 Organisations :
 - search1
 - list
 - create
 - create from XML
 - dumpxml
 - trust(other)




 De:    Dave Sullivan <dsulliva@redhat.com>
 À:     Mailing Red Hat - Consult <consult-list@redhat.com>
 Cc:    bholden@redhat.com
 Sujet:     [Consult-list] rhnApiCode
 Date:  14/04/2010 21:38:15
 Client de messagerie:  Mozilla/5.0 (X11; U; Linux x86_64; en-US;
 rv:1.9.1.8) Gecko/20100301 Fedora/3.0.3-1.fc11 Lightning/1.0b2pre
 Thunderbird/3.0.3


 FYI,

 I wrote some code that pulls from the rhn apis to list errata based
 on 
 the following inputs.

   -system profile (list of rpm packages from a machine)
   -a set start date
   -an end date
   -a channel

                 Some of this code was borrowed from here.....thanks
                 bholden for getting 
                 me started.

                 http://people.redhat.com/bholden/scripts/

                 Hope this is helpful for someone.

=cut


http://github.com/aparsons/spacecmd
http://people.redhat.com/aparsons/



# Commandes dans les scripts :
# - help | rien => pod2usage
