#!/usr/bin/perl
use strict;
use warnings;
use Frontier::Client;
use Frontier::RPC2;
use Data::Dumper;

my $HOST = 'sat.octothorpe.fr';
my $user = 'rhn-admin';
my $pass = 'Lsld4vm';

my $client = Frontier::Client->new( url => "http://$HOST/rpc/api" );
my $session = $client->call( 'auth.login', $user, $pass );

print STDERR Dumper( \$session );
print "here\n";
my $org = $client->call(
    'org.create',
    $session,
    "testorg",
    "test-admin",
    "redhat",
    "Mr.",
    "shadowman",
    "test",
    'test@example.com',
    Frontier::RPC2::Boolean->new(0),
    );
print Dumper( \$org);

