#!/usr/bin/perl
use strict;
use warnings;

use lib qw( . .. lib ../lib );
use RHNC;
use RHNC::Session;
use RHNC::Channel;
use Carp;
use Getopt::Long qw(GetOptionsFromArray);
use Data::Dumper;

use vars qw( $rhnc );

=head1 COMMANDS

#
# Subs
#

=head2 add_packages

TODO

=cut

sub add_packages {
    carp "not implemented yet";

    return;
}

sub create {
    my @args = @_;

    # FIXME : this cannot work as it is. Add argument parsing here
    # using Getopt::Long
    my $rc = RHNC::Channel->create( rhnc => $rhnc, @args );

    return $rc;
}

sub destroy {
    my @args = @_;

    foreach my $kname (@args) {
        my $chan = RHNC::Channel->get( $rhnc, $kname );
        if ( defined $chan ) {
            $chan->delete( $rhnc, $kname );
        }
    }

    return 1;
}

=head2 gdp|get_detail_packages

Print details for packages in the channel.

=cut

sub get_detail_packages {
    my (@args) = @_;

    foreach my $chan (@args) {
        my $channel = RHNC::Channel::get( $rhnc, $chan );

        print 'Packages for channel '
          . $channel->label . ' ('
          . $channel->name() . ")\n";
        my @plist = $channel->packages();
        @plist = sort {
            "$a->{name}-$a->{version}-$a->{release}-$a->{arch_label}" cmp
              "$b->{name}-$b->{version}-$b->{release}-$b->{arch_label}"
        } @plist;

        #@plist = sort { $a->{last_modified} cmp $b->{last_modified} } @plist;
        foreach my $p (@plist) {
            print "  $p->{name}-$p->{version}-$p->{release}-$p->{arch_label}: ";
            print join ", ", map { "$_=$p->{$_}" } qw( id last_modified);
            print "\n";
        }
    }

    return 1;
}

=head2 gd|get_details

Print detailed information about the given channel(s).

=cut

sub get_details {
    my @args = @_;

    my $chan;
    while ( $chan = shift @args ) {
        print "$chan:\n";
        my $channel = RHNC::Channel::get( $rhnc, $chan );
        $channel->nbpackages();
        foreach my $k ( sort ( keys %{$channel} ) ) {
            next if $k eq 'rhnc';
            if ( $k eq 'packages' ) {
                print "$k: ";
                my %pkg = map { $_->{name} => 1 } @{ $channel->{$k} };
                print join( ', ', sort keys %pkg );
                print "\n";
            }
            else {
                print "  $k : $channel->{$k}\n";
            }
        }
    }

    return 1;
}

=head2 l|list

List channels

=cut

sub list {
    my @args = @_;
    my ( $verbose );

    my $result = GetOptionsFromArray( \@args, 'verbose|v' => \$verbose, );

    my @channel = RHNC::Channel->list($rhnc);

    my $nr = 0;
    foreach my $chan (@channel) {
        my $parent = $chan->parent_label();
        my $child  = $chan->label();
        if ( $parent ne '' ) { print "  "; }
        printf(
            "%-44s: %5d pkg, %5d systems, %s, %-40s\n",
            $chan->label(),         $chan->nbpackages(), $chan->systems(),
            $chan->provider_name(), $chan->name(),
        );
    }
    print "\nTotal: " . scalar(@channel) . " Channels\n";

    return 1;
}

=head2 la|list_arches

Prints a list of available arches.

=cut

sub list_arches {
    my @args = @_;

    my %arches = RHNC::Channel->list_arches($rhnc);

    print "Arches available: \n";
    foreach my $a ( keys %arches ) {
        print "$a: $arches{$a}\n";
    }

    return 1;
}

=head2 le|list_errata

List all available errata in the channel(s)

=cut

sub list_errata {
    my @args = @_;
    my $channel;
    while ( $channel = shift @args ) {
        my %errata = RHNC::Channel->list_errata( $rhnc, $channel );
        foreach my $erratum ( sort keys %errata ) {
            print
"$erratum ($errata{$erratum}{issue_date}): $errata{$erratum}{synopsis}\n";
        }
    }

    return 1;
}

=head2 llp|list_last_packages

TODO

=cut

sub list_latest_packages {
    my @args = @_;
    my $label_or_id;

    while ( $label_or_id = shift @args ) {
        my $chan = RHNC::Channel::get( $rhnc, $label_or_id );
        my @pkglist = $chan->latest_packages();

        print '-' x 60  . "\n";
        print 'Latest packages for channel ' . $chan->label() . "\n";
        print '-' x 60  . "\n";
        foreach my $pkg (@pkglist) {
            print "$pkg->{name}-$pkg->{version}-$pkg->{release}-$pkg->{arch_label}: $pkg->{id}\n";
        }
    }

    return 1;
}

=head2 lp|list_packages

List packages (NVRA) in the channel(s)

=cut

sub list_packages {
    my @args = @_;
    my $label_or_id;

    while ( $label_or_id = shift @args ) {
        my $chan = RHNC::Channel::get( $rhnc, $label_or_id );
        my @pkglist = $chan->packages();

        print '-' x 60  . "\n";
        print 'Packages for channel ' . $chan->label() . "\n";
        print '-' x 60 . "\n";
        foreach my $pkg (@pkglist) {
            print
"$pkg->{name}-$pkg->{version}-$pkg->{release}-$pkg->{arch_label}: $pkg->{id}\n";
        }
    }

    return 1;
}

=head2 ls|list_systems

List the systems subscribed to the channel(s).

=cut

sub list_systems {
    my @args = @_;
    my $channel;

    while ( $channel = shift @args ) {
        my %systems = RHNC::Channel->list_systems( $rhnc, $channel );
        foreach my $system ( sort keys %systems ) {
            print "$system: $systems{$system}\n";
        }
    }

    return 1;
}

=head2 rm_packages

TODO

=cut

sub rm_packages {
    my @args = @_;

    carp "not implemented yet";

    return 1;
}

#
# Main
#

$rhnc = RHNC::Session->new();

#print "API version : ", $rhnc->apiversion(), " | ";
#print "Org ID : ",      $rhnc->org_id(),     "\n";

my @args = @ARGV;
my $cmd  = shift @args;

SWITCH: for ($cmd) {
    /^(?:ap|AddPackages|add_packages)$/i && add_packages(@args) && last SWITCH;
    /^(?:c|Create)$/i                    && create(@args)       && last SWITCH;
    /^(?:d|Destroy)$/i                   && destroy(@args)      && last SWITCH;
    /^(?:gdp|GetDetailPackages|get_detail_packages)$/i
      && get_detail_packages(@args)
      && last SWITCH;
    /^(?:gd|GetDetails|get_details)$/i && get_details(@args) && last SWITCH;
    /^(?:l|li|lis|list)$/i             && list(@args)        && last SWITCH;
    /^(?:la|ListArches|list_arches)$/i && list_arches(@args) && last SWITCH;
    /^(?:le|ListErrata|list_errata)$/i && list_errata(@args) && last SWITCH;
    /^(?:llp|ListLatestPackages|list_latest_packages)$/i
      && list_latest_packages(@args)
      && last SWITCH;
    /^(?:lp|ListPackages|list_packages)$/i
      && list_packages(@args)
      && last SWITCH;
    /^(?:ls|ListSystems|list_systems)$/i && list_systems(@args) && last SWITCH;
    /^(?:rp|RmPackages|rm_packages)$/i   && rm_packages(@args)  && last SWITCH;
}

